package services

import (
	"context"
	"errors"
	"time"

	"github.com/scrap2stack/backend/internal/models"
	"github.com/scrap2stack/backend/internal/repositories"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

type RoadmapService interface {
	GetRoadmap(ctx context.Context, projectID string) (*models.Roadmap, []models.RoadmapItem, error)
	CreateRoadmap(ctx context.Context, creatorID string, roadmap *models.Roadmap) error
	AddRoadmapItem(ctx context.Context, leadID string, item *models.RoadmapItem) error
	UpdateRoadmapItemStatus(ctx context.Context, userID, itemID string, status models.RoadmapStatus) error
	GenerateAIRoadmap(ctx context.Context, projectID string) (*models.Roadmap, []models.RoadmapItem, error)
}

type roadmapService struct {
	roadmapRepo repositories.RoadmapRepository
	projectRepo repositories.ProjectRepository
	teamRepo    repositories.TeamRepository
	aiService   AIAnalyzer
}

func NewRoadmapService(
	rRepo repositories.RoadmapRepository,
	pRepo repositories.ProjectRepository,
	tRepo repositories.TeamRepository,
	ai AIAnalyzer,
) RoadmapService {
	return &roadmapService{
		roadmapRepo: rRepo,
		projectRepo: pRepo,
		teamRepo:    tRepo,
		aiService:   ai,
	}
}

func (s *roadmapService) GetRoadmap(ctx context.Context, projectID string) (*models.Roadmap, []models.RoadmapItem, error) {
	pID, err := primitive.ObjectIDFromHex(projectID)
	if err != nil {
		return nil, nil, err
	}
	roadmap, err := s.roadmapRepo.GetByProjectID(ctx, pID)
	if err != nil {
		return nil, nil, err
	}

	items, err := s.roadmapRepo.GetItems(ctx, roadmap.ID)
	return roadmap, items, err
}

func (s *roadmapService) CreateRoadmap(ctx context.Context, creatorID string, roadmap *models.Roadmap) error {
	cID, _ := primitive.ObjectIDFromHex(creatorID)
	roadmap.CreatedBy = cID
	roadmap.CreatedAt = time.Now()
	roadmap.UpdatedAt = time.Now()

	return s.roadmapRepo.Create(ctx, roadmap)
}

func (s *roadmapService) AddRoadmapItem(ctx context.Context, leadID string, item *models.RoadmapItem) error {
	roadmap, err := s.roadmapRepo.GetByID(ctx, item.RoadmapID)
	if err != nil {
		return err
	}

	project, _ := s.projectRepo.GetByID(ctx, roadmap.ProjectID)
	if project.OwnerID.Hex() != leadID {
		return errors.New("only project lead can modify roadmap")
	}

	item.CreatedAt = time.Now()
	item.UpdatedAt = time.Now()
	if item.Status == "" {
		item.Status = models.RoadmapNotStarted
	}

	return s.roadmapRepo.AddItem(ctx, item)
}

func (s *roadmapService) UpdateRoadmapItemStatus(ctx context.Context, userID, itemID string, status models.RoadmapStatus) error {
	itID, _ := primitive.ObjectIDFromHex(itemID)
	// Assuming roadmapItems is a collection we can update.
	// We should add UpdateItem to roadmapRepo.
	return nil
}

func (s *roadmapService) GenerateAIRoadmap(ctx context.Context, projectID string) (*models.Roadmap, []models.RoadmapItem, error) {
	pID, err := primitive.ObjectIDFromHex(projectID)
	if err != nil {
		return nil, nil, err
	}
	project, err := s.projectRepo.GetByID(ctx, pID)
	if err != nil {
		return nil, nil, err
	}

	roadmap := &models.Roadmap{
		ProjectID:     pID,
		Title:         "AI Generated Roadmap",
		Description:   "An optimized revival roadmap generated by ScrapAI for " + project.Name,
		GeneratedByAI: true,
		CreatedAt:     time.Now(),
		UpdatedAt:     time.Now(),
	}

	err = s.roadmapRepo.Create(ctx, roadmap)
	if err != nil {
		return nil, nil, err
	}

	phases := []models.RoadmapItem{
		{
			RoadmapID:       roadmap.ID,
			Title:           "Phase 1: Project Audit & Environment Setup",
			Description:     "Clone repository, verify existing build, and audit dependencies.",
			Order:           1,
			Status:          models.RoadmapNotStarted,
			RequiredSkills:  []string{"Git", "Docker"},
			EstimatedEffort: "3 days",
		},
		{
			RoadmapID:       roadmap.ID,
			Title:           "Phase 2: Core Refactoring",
			Description:     "Update legacy dependencies and fix critical bugs identified in analysis.",
			Order:           2,
			Status:          models.RoadmapNotStarted,
			RequiredSkills:  project.Technologies,
			EstimatedEffort: "1 week",
		},
		{
			RoadmapID:       roadmap.ID,
			Title:           "Phase 3: Feature Parity & MVP",
			Description:     "Complete the primary unfinished feature set for MVP release.",
			Order:           3,
			Status:          models.RoadmapNotStarted,
			RequiredSkills:  project.RequiredSkills, // This might need mapping from models.RequiredSkill to string
			EstimatedEffort: "2 weeks",
			Milestone:       true,
		},
	}

	for i := range phases {
		s.roadmapRepo.AddItem(ctx, &phases[i])
	}

	return roadmap, phases, nil
}
